--liquibase formatted sql
--changeset admin:3 splitStatements:true context:test

INSERT INTO VTL_CATEGORY (ID,PARENT_ID,CODE,NAME,REMARK,SEQ,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) VALUES
	 (1,      0,   'vtl_address',                 '地址区域分类','地址区域分类',1,'N',1,CURRENT_TIMESTAMP(),1,CURRENT_TIMESTAMP()),
	 (1001,   1,   'vtl_address_shaanxi',         '陕西省',      NULL,         1,'N',1,CURRENT_TIMESTAMP(),1,CURRENT_TIMESTAMP()),
	 (1001001,1001,'vtl_address_shaanxi_xian',    '西安市',      NULL,         1,'N',1,CURRENT_TIMESTAMP(),1,CURRENT_TIMESTAMP()),
	 (1001002,1001,'vtl_address_shaanxi_xianyang','咸阳市',      NULL,         2,'N',1,CURRENT_TIMESTAMP(),1,CURRENT_TIMESTAMP()),
	 (1001003,1001,'vtl_address_shaanxi_hanzhong','汉中市',      NULL,         3,'Y',1,CURRENT_TIMESTAMP(),1,CURRENT_TIMESTAMP()),
	 (1002,1,      'vtl_address_sichuan',         '四川省',      NULL,         2,'N',1,CURRENT_TIMESTAMP(),1,CURRENT_TIMESTAMP()),
	 (1002001,1002,'vtl_address_sichuan_chengdou','成都市',      NULL,         1,'N',1,CURRENT_TIMESTAMP(),1,CURRENT_TIMESTAMP());

--INSERT INTO VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) VALUES (90001001,          0,              'DIR',  '权限管理',             'ep:lollipop',  'Y',NULL,99999, NULL,                       '/permission',                   NULL,'N',NULL,1,CURRENT_TIMESTAMP(),1,CURRENT_TIMESTAMP());
--INSERT INTO VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) VALUES (90001001001,       90001001,       'MENU', '页面权限',             NULL,           'Y',NULL,1,     'PermissionPage',           '/permission/page/index',        NULL,'N',NULL,1,CURRENT_TIMESTAMP(),1,CURRENT_TIMESTAMP());
--INSERT INTO VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) VALUES (90001001002,       90001001,       'DIR',  '按钮权限',             NULL,           'Y',NULL,2,     NULL,                       '/permission/button',          NULL,'N',NULL,1,CURRENT_TIMESTAMP(),1,CURRENT_TIMESTAMP());
--INSERT INTO VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) VALUES (90001001002001,    90001001002,    'MENU', '路由返回按钮权限',      NULL,           'Y',NULL,1,     'PermissionButtonRouter',   '/permission/button/index',    NULL,'N',NULL,1,CURRENT_TIMESTAMP(),1,CURRENT_TIMESTAMP());
--INSERT INTO VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) VALUES (90001001002002,    90001001002,    'MENU', '登录接口返回按钮权限',  NULL,            'Y',NULL,2,     'PermissionButtonLogin',   '/permission/button/perms',    NULL,'N',NULL,1,CURRENT_TIMESTAMP(),1,CURRENT_TIMESTAMP());
