--liquibase formatted sql
--changeset admin:2 splitStatements:true

-- 用户
insert into VTL_USER (ID,USERNAME,NICKNAME,PASSWORD,ID_CARD,GENDER,EMAIL,MOBILE,SECRET_KEY,DISABLED,DELETED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1,'admin','管理员','$2a$10$skK/p5CVKEGnrZToZzof9ejJOEynmjf6Gn1egtsa/B.2wFg1sxmx6',null,null,null,null,null,'N','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_USER (ID,USERNAME,NICKNAME,PASSWORD,ID_CARD,GENDER,EMAIL,MOBILE,SECRET_KEY,DISABLED,DELETED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (2,'sysAdmin','系统管理员','$2a$10$skK/p5CVKEGnrZToZzof9ejJOEynmjf6Gn1egtsa/B.2wFg1sxmx6',null,null,null,null,null,'N','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_USER (ID,USERNAME,NICKNAME,PASSWORD,ID_CARD,GENDER,EMAIL,MOBILE,SECRET_KEY,DISABLED,DELETED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (3,'guest','游客','$2a$10$skK/p5CVKEGnrZToZzof9ejJOEynmjf6Gn1egtsa/B.2wFg1sxmx6',null,null,null,null,null,'N','N',1,current_timestamp(),1,current_timestamp());

-- 角色
insert into VTL_ROLE (ID, NAME, CODE, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1, '管理员', 'admin', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_ROLE (ID, NAME, CODE, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (2, '普通用户', 'common', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_ROLE (ID, NAME, CODE, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (3, '游客', 'guest', 3, 'N', null, 1, current_timestamp(), 1, current_timestamp());

-- 部门
insert into VTL_DEPT (ID, PARENT_ID, NAME, SEQ, DISABLED, DELETED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1,           0,        'VTL科技',   1, 'N', 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, SEQ, DISABLED, DELETED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1001,        1,        '西安分部',   1, 'N', 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, SEQ, DISABLED, DELETED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1001001,     1001,     '财务部',     1, 'N', 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, SEQ, DISABLED, DELETED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1001002,     1001,     '研发中心',   2, 'N', 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, SEQ, DISABLED, DELETED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1001002001,  1001002,  '研发一部',   1, 'N', 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, SEQ, DISABLED, DELETED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1001002002,  1001002,  '研发二部',   2, 'N', 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, SEQ, DISABLED, DELETED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1001003,     1001,     '销售部',     3, 'N', 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, SEQ, DISABLED, DELETED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1002,        1,        '北京分部',   2, 'N', 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, SEQ, DISABLED, DELETED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1002002,     1002,     '研发一部',    1, 'N', 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, SEQ, DISABLED, DELETED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1002003,     1002,     '销售部',     2, 'N', 'N', null, 1, current_timestamp(), 1, current_timestamp());

-- 岗位
insert into VTL_POST (ID, NAME, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1, '董事长', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_POST (ID, NAME, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (2, '人力资源', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_POST (ID, NAME, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (3, '开发工程师', 3, 'N', null, 1, current_timestamp(), 1, current_timestamp());

-- 字典类型
insert into VTL_DICT_TYPE (ID, NAME, CODE, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1, '停用/启用', 'vtl_disabled', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_TYPE (ID, NAME, CODE, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (2, '是/否', 'vtl_yes_no', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_TYPE (ID, NAME, CODE, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (3, '菜单类型', 'vtl_menu_type', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_TYPE (ID, NAME, CODE, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (4, '菜单打开方式', 'vtl_menu_open_type', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_TYPE (ID, NAME, CODE, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (5, '用户性别', 'vtl_user_gender', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_TYPE (ID, NAME, CODE, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (6, '成功/失败', 'vtl_succeeded', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_TYPE (ID, NAME, CODE, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (7, '登录类型', 'vtl_login_type', null, 1, current_timestamp(), 1, current_timestamp());

-- 字典：停用/启用
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (10001, 'vtl_disabled', 'N', '启用', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (10002, 'vtl_disabled', 'Y', '停用', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
-- 字典：是/否
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (20001, 'vtl_yes_no', 'Y', '是', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (20002, 'vtl_yes_no', 'N', '否', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
-- 字典：成功/失败
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (30001, 'vtl_succeeded', 'Y', '成功', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (30002, 'vtl_succeeded', 'N', '失败', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
-- 字典：用户性别
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (40001, 'vtl_user_gender', 'male', '男', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (40002, 'vtl_user_gender', 'female', '女', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (40003, 'vtl_user_gender', 'unknow', '未知', 3, 'N', null, 1, current_timestamp(), 1, current_timestamp());
-- 字典：登录类型
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (50001, 'vtl_login_type', 'LOGIN', '登录', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (50002, 'vtl_login_type', 'LOGOUT', '注销', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (50003, 'vtl_login_type', 'KICK_OUT', '被踢下线', 3, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (50004, 'vtl_login_type', 'REPLACED', '被顶下线', 4, 'N', null, 1, current_timestamp(), 1, current_timestamp());
-- 字典：菜单类型
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (60001, 'vtl_menu_type', 'MENU', '菜单', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (60002, 'vtl_menu_type', 'BTN', '按钮', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (60003, 'vtl_menu_type', 'IFRAME', '内嵌页面', 3, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (60004, 'vtl_menu_type', 'URL', '外链', 4, 'N', null, 1, current_timestamp(), 1, current_timestamp());

-- 配置
insert into VTL_CONFIG (ID, NAME, CODE, VAL, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1, '用户管理-初始密码', 'vtl_user_init_password', 'aday.fun', null, 1, current_timestamp(), 1, current_timestamp());
--
------ TYPE：菜单类型。{ MENU=菜单; BTN=按钮; IFRAME=内嵌页面；URL=外链页面；}。前端对应：（0代表菜单、1代表iframe、2代表外链、3代表按钮）
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1001,0,'MENU','通知公告','NoticeManagePage','/vitality/system/notice/index',null,1,null,'ep:bell',null,null,null,null,'system:notice:view',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1001001,1001,'BTN','通知公告-查询',null,null,null,1,null,null,null,null,null,null,'system:notice:query',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1001002,1001,'BTN','通知公告-创建',null,null,null,2,null,null,null,null,null,null,'system:notice:create',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1001003,1001,'BTN','通知公告-更新',null,null,null,3,null,null,null,null,null,null,'system:notice:update',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1001004,1001,'BTN','通知公告-删除',null,null,null,4,null,null,null,null,null,null,'system:notice:delete',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1002,0,'MENU','我的消息','MyMessagePage','/vitality/system/message/index',null,2,null,'ep:chat-dot-round',null,null,null,null,'system:my:message',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1002001,1002,'BTN','我的消息-查询',null,null,null,1,null,null,null,null,null,null,'system:message:query',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1002002,1002,'BTN','我的消息-创建',null,null,null,2,null,null,null,null,null,null,'system:message:create',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1002003,1002,'BTN','我的消息-更新',null,null,null,3,null,null,null,null,null,null,'system:message:update',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1002004,1002,'BTN','我的消息-删除',null,null,null,4,null,null,null,null,null,null,'system:message:delete',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1003,0,'MENU','我的流程','MyFlowPage','/vitality/system/flow/index',null,3,null,'ri:flow-chart',null,null,null,null,'system:my:flow',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1003001,1003,'BTN','我的流程-查询',null,null,null,1,null,null,null,null,null,null,'system:flow:query',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1003002,1003,'BTN','我的流程-创建',null,null,null,2,null,null,null,null,null,null,'system:flow:create',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1003003,1003,'BTN','我的流程-更新',null,null,null,3,null,null,null,null,null,null,'system:flow:update',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1003004,1003,'BTN','我的流程-删除',null,null,null,4,null,null,null,null,null,null,'system:flow:delete',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());


insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011,0,'MENU','系统管理','SystemManageMenu','/vitality/system',null,11,null,'ep:setting',null,null,null,null,'system:manage:view',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011001,10011,'MENU','菜单管理','MenuManagePage','/vitality/system/menu/index',null,1,null,'ep:menu',null,null,null,null,'system:menu:view',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011001001,10011001,'BTN','菜单-查询',null,null,null,1,null,null,null,null,null,null,'system:menu:query',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011001002,10011001,'BTN','菜单-创建',null,null,null,2,null,null,null,null,null,null,'system:menu:create',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011001003,10011001,'BTN','菜单-更新',null,null,null,3,null,null,null,null,null,null,'system:menu:update',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011001004,10011001,'BTN','菜单-删除',null,null,null,4,null,null,null,null,null,null,'system:menu:delete',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011002,10011,'MENU','部门管理','DeptManagePage','/vitality/system/dept/index',null,2,null,'ri:organization-chart',null,null,null,null,'system:dept:view',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011002001,10011002,'BTN','部门-查询',null,null,null,1,null,null,null,null,null,null,'system:dept:query',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011002002,10011002,'BTN','部门-创建',null,null,null,2,null,null,null,null,null,null,'system:dept:create',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011002003,10011002,'BTN','部门-更新',null,null,null,3,null,null,null,null,null,null,'system:dept:update',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011002004,10011002,'BTN','部门-删除',null,null,null,4,null,null,null,null,null,null,'system:dept:delete',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011003,    10011,      'MENU', '岗位管理', 'PostManagePage',   '/vitality/system/post/index',  null,   3,null,'fa-solid:user-tie', null,null,null,null,'system:post:view',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011003001, 10011003,   'BTN',  '岗位-查询',null,               null,                           null,   1,null,null,                null,null,null,null,'system:post:query',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011003002, 10011003,   'BTN',  '岗位-创建',null,               null,                           null,   2,null,null,                null,null,null,null,'system:post:create',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011003003, 10011003,   'BTN',  '岗位-更新',null,               null,                           null,   3,null,null,                null,null,null,null,'system:post:update',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011003004, 10011003,   'BTN',  '岗位-删除',null,               null,                           null,   4,null,null,                null,null,null,null,'system:post:delete',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011004,    10011,      'MENU', '用户管理', 'UserManagePage',   '/vitality/system/user/index',  null,   4,null,'ep:user-filled',    null,null,null,null,'system:user:view',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011004001, 10011004,   'BTN',  '用户-查询',null,               null,                           null,   1,null,null,                null,null,null,null,'system:user:query',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011004002, 10011004,   'BTN',  '用户-创建',null,               null,                           null,   2,null,null,                null,null,null,null,'system:user:create',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011004003, 10011004,   'BTN',  '用户-更新',null,               null,                           null,   3,null,null,                null,null,null,null,'system:user:update',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011004004, 10011004,   'BTN',  '用户-删除',null,               null,                           null,   4,null,null,                null,null,null,null,'system:user:delete',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011005,    10011,      'MENU', '角色管理', 'RoleManagePage',   '/vitality/system/role/index',  null,   5,null,'fa-solid:users',    null,null,null,null,'system:role:view',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011005001, 10011005,   'BTN',  '角色-查询',null,               null,                           null,   1,null,null,                null,null,null,null,'system:role:query',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011005002, 10011005,   'BTN',  '角色-创建',null,               null,                           null,   2,null,null,                null,null,null,null,'system:role:create',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011005003, 10011005,   'BTN',  '角色-更新',null,               null,                           null,   3,null,null,                null,null,null,null,'system:role:update',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011005004, 10011005,   'BTN',  '角色-删除',null,               null,                           null,   4,null,null,                null,null,null,null,'system:role:delete',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011006,    10011,      'MENU', '分类管理', 'CategoryManagePage',   '/vitality/system/category/index',  null,   6,null,'fa-solid:stream',   null,null,null,null,'system:category:view',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011006001, 10011006,   'BTN',  '分类-查询',null,                   null,                               null,   1,null,null,                null,null,null,null,'system:category:query',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011006002, 10011006,   'BTN',  '分类-创建',null,                   null,                               null,   2,null,null,                null,null,null,null,'system:category:create',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011006003, 10011006,   'BTN',  '分类-更新',null,                   null,                               null,   3,null,null,                null,null,null,null,'system:category:update',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011006004, 10011006,   'BTN',  '分类-删除',null,                   null,                               null,   4,null,null,                null,null,null,null,'system:category:delete',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007,    10011,      'MENU', '字典管理', 'DictManagePage',   '/vitality/system/dict/index',  null,   7,null,'fa-solid:book-open',    null,null,null,null,'system:dict:view',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007001, 10011007,   'BTN',  '字典-类型-查询',null,               null,                           null,   1,null,null,                    null,null,null,null,'system:dictType:query',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007002, 10011007,   'BTN',  '字典-类型-创建',null,               null,                           null,   2,null,null,                    null,null,null,null,'system:dictType:create',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007003, 10011007,   'BTN',  '字典-类型-更新',null,               null,                           null,   3,null,null,                    null,null,null,null,'system:dictType:update',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007004, 10011007,   'BTN',  '字典-类型-删除',null,               null,                           null,   4,null,null,                    null,null,null,null,'system:dictType:delete',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007005, 10011007,   'BTN',  '字典-数据-查询',null,               null,                           null,   1,null,null,                    null,null,null,null,'system:dictData:query',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007006, 10011007,   'BTN',  '字典-数据-创建',null,               null,                           null,   2,null,null,                    null,null,null,null,'system:dictData:create',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007007, 10011007,   'BTN',  '字典-数据-更新',null,               null,                           null,   3,null,null,                    null,null,null,null,'system:dictData:update',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007008, 10011007,   'BTN',  '字典-数据-删除',null,               null,                           null,   4,null,null,                    null,null,null,null,'system:dictData:delete',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011008,    10011,      'MENU', '配置管理', 'ConfigManagePage',   '/vitality/system/config/index',  null,   8,null,'ep:set-up',   null,null,null,null,'system:config:view',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011008001, 10011008,   'BTN',  '配置-查询',null,                   null,                           null,   1,null,null,          null,null,null,null,'system:config:query',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011008002, 10011008,   'BTN',  '配置-创建',null,                   null,                           null,   2,null,null,          null,null,null,null,'system:config:create',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011008003, 10011008,   'BTN',  '配置-更新',null,                   null,                           null,   3,null,null,          null,null,null,null,'system:config:update',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011008004, 10011008,   'BTN',  '配置-删除',null,                   null,                           null,   4,null,null,          null,null,null,null,'system:config:delete',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011009,    10011,      'MENU', '文件管理', 'FileManagePage',   '/vitality/system/oss/index',       null,   9,null,'fa-solid:file', null,null,null,null,'system:oss:view',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011009001, 10011009,   'BTN',  '文件-查询',null,                   null,                           null,   1,null,null,            null,null,null,null,'system:oss:query',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011009002, 10011009,   'BTN',  '文件-创建',null,                   null,                           null,   2,null,null,            null,null,null,null,'system:oss:create',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011009003, 10011009,   'BTN',  '文件-更新',null,                   null,                           null,   3,null,null,            null,null,null,null,'system:oss:update',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011009004, 10011009,   'BTN',  '文件-删除',null,                   null,                           null,   4,null,null,            null,null,null,null,'system:oss:delete',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());


insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10021,0,'MENU','系统监控','SystemMonitor','/vitality/system/monitor',null,21,null,'ep:monitor',null,null,null,null,'monitor:system:view',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10021001,10021,'MENU','应用监控','MonitorApplicationPage','/vitality/monitor/application/index',null,1,null,'fa-solid:chart-line',null,null,null,null,'monitor:application:query',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10021002,10021,'MENU','缓存监控','MonitorCachePage','/vitality/monitor/cache/index',null,2,null,'ep:data-line',null,null,null,null,'monitor:cache:query',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10021003,      10021,'MENU','在线用户',       'MonitorUserOnlinePage','/vitality/monitor/online/index',null,3,null,'ri:user-voice-fill',null,null,null,null,'monitor:userOnline:view',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10021003001,10021003,'BTN', '在线用户-查询',   null,null,null,1,null,null,null,null,null,null,'monitor:userOnline:query',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10021003002,10021003,'BTN', '在线用户-下线',   null,null,null,2,null,null,null,null,null,null,'monitor:userOnline:kickOut',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10021004,      10021,'MENU','登录日志',       'MonitorLoginLogPage','/vitality/monitor/log/login/index',null,4,null,'ri:file-text-fill',null,null,null,null,'monitor:logLogin:view',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10021004001,10021004,'BTN', '登录日志-查询',   null,null,null,1,null,null,null,null,null,null,'monitor:logLogin:query',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10021004002,10021004,'BTN', '登录日志-删除',   null,null,null,2,null,null,null,null,null,null,'monitor:logLogin:delete',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10021005,      10021,'MENU','操作日志',       'MonitorOperationLogPage','/vitality/monitor/log/operation/index',null,5,null,'ri:file-text-fill',null,null,null,null,'monitor:logOperation:view',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10021005001,10021005,'BTN', '操作日志-查询',   null,null,null,1,null,null,null,null,null,null,'monitor:logOperation:query',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10021005002,10021005,'BTN', '操作日志-删除',   null,null,null,2,null,null,null,null,null,null,'monitor:logOperation:delete',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10021006,      10021,'MENU','异常日志',       'MonitorErrorLogPage','/vitality/monitor/log/error/index',null,6,null,'ri:file-text-fill',null,null,null,null,'monitor:logError:view',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10021006001,10021006,'BTN', '异常日志-查询',   null,null,null,1,null,null,null,null,null,null,'monitor:logError:query',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10021006002,10021006,'BTN', '异常日志-删除',   null,null,null,2,null,null,null,null,null,null,'monitor:logError:delete',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());


insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10081,0,'MENU','开发工具','DevelopmentTool','/vitality/system/tool',null,81,null,'fa-solid:tools',null,null,null,null,'tool:development:view',null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10081001,10081,'IFRAME','接口文档','ToolApiDocumentPage','/vitality/system/tool/api',null,1,null,'ep:document',null,null,null,null,'tool:api:view','http://localhost:8080/doc.html','N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());

-- EXTRA_ICON iconfont 配置：IF-icon-vitality-new svg: [以 IF- 开头] [icon-vitality-: 为 iconfont.json 中 css_prefix_text 配置的值] [new: 为 iconfont.json 中 font_class 配置的值] [svg: 为文件格式]
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10091,0,'URL','个人博客',            'https://home.aday.fun',                    '/vitality/aday/fun/home',       null,91,null,'ep:link',                    'IF-icon-vitality-fire svg', null,null,null,null,null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10092,0,'URL','Vitality 管理系统',   'https://vitality.aday.fun',                '/vitality/aday/fun/vitality',   null,92,null,'ep:link',                    'IF-icon-vitality-new svg',  null,null,null,null,null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10093,0,'URL','GitHub',              'https://github.com/mengweijin/vitality',  '/vitality/github',             null,93,null,'ri:github-fill',              null,                        null,null,null,null,null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,DISABLED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10094,0,'URL','Gitee',               'https://gitee.com/mengweijin/vitality',   '/vitality/gitee',              null,94,null,'IF-icon-vitality-gitee svg',  null,                        null,null,null,null,null,'N','N','N','N','Y','Y','N',1,current_timestamp(),1,current_timestamp());

