--liquibase formatted sql
--changeset admin:2 splitStatements:true

-- 用户
insert into VTL_USER (ID,USERNAME,NICKNAME,PASSWORD,ID_CARD,GENDER,EMAIL,MOBILE,SECRET_KEY,DISABLED,DELETED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1,'admin','管理员','$2a$10$skK/p5CVKEGnrZToZzof9ejJOEynmjf6Gn1egtsa/B.2wFg1sxmx6',null,null,null,null,null,'N','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_USER (ID,USERNAME,NICKNAME,PASSWORD,ID_CARD,GENDER,EMAIL,MOBILE,SECRET_KEY,DISABLED,DELETED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (2,'sysAdmin','系统管理员','$2a$10$skK/p5CVKEGnrZToZzof9ejJOEynmjf6Gn1egtsa/B.2wFg1sxmx6',null,null,null,null,null,'N','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_USER (ID,USERNAME,NICKNAME,PASSWORD,ID_CARD,GENDER,EMAIL,MOBILE,SECRET_KEY,DISABLED,DELETED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (3,'guest','游客','$2a$10$skK/p5CVKEGnrZToZzof9ejJOEynmjf6Gn1egtsa/B.2wFg1sxmx6',null,null,null,null,null,'N','N',1,current_timestamp(),1,current_timestamp());

-- 角色
insert into VTL_ROLE (ID, NAME, CODE, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1, '管理员', 'admin', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_ROLE (ID, NAME, CODE, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (2, '普通用户', 'common', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_ROLE (ID, NAME, CODE, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (3, '游客', 'guest', 3, 'N', null, 1, current_timestamp(), 1, current_timestamp());

-- 部门
insert into VTL_DEPT (ID, PARENT_ID, NAME, SEQ, DISABLED, DELETED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1,           0,        'VTL科技',   1, 'N', 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, SEQ, DISABLED, DELETED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1001,        1,        '西安分部',   1, 'N', 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, SEQ, DISABLED, DELETED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1001001,     1001,     '财务部',     1, 'N', 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, SEQ, DISABLED, DELETED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1001002,     1001,     '研发中心',   2, 'N', 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, SEQ, DISABLED, DELETED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1001002001,  1001002,  '研发一部',   1, 'N', 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, SEQ, DISABLED, DELETED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1001002002,  1001002,  '研发二部',   2, 'N', 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, SEQ, DISABLED, DELETED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1001003,     1001,     '销售部',     3, 'N', 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, SEQ, DISABLED, DELETED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1002,        1,        '北京分部',   2, 'N', 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, SEQ, DISABLED, DELETED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1002002,     1002,     '研发一部',    1, 'N', 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, SEQ, DISABLED, DELETED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1002003,     1002,     '销售部',     2, 'N', 'N', null, 1, current_timestamp(), 1, current_timestamp());

-- 岗位
insert into VTL_POST (ID, NAME, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1, '董事长', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_POST (ID, NAME, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (2, '人力资源', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_POST (ID, NAME, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (3, '开发工程师', 3, 'N', null, 1, current_timestamp(), 1, current_timestamp());

-- 字典类型
insert into VTL_DICT_TYPE (ID, NAME, CODE, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1, '停用/启用', 'vtl_disabled', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_TYPE (ID, NAME, CODE, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (2, '是/否', 'vtl_yes_no', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_TYPE (ID, NAME, CODE, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (3, '菜单类型', 'vtl_menu_type', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_TYPE (ID, NAME, CODE, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (4, '菜单打开方式', 'vtl_menu_open_type', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_TYPE (ID, NAME, CODE, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (5, '用户性别', 'vtl_user_gender', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_TYPE (ID, NAME, CODE, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (6, '成功/失败', 'vtl_succeeded', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_TYPE (ID, NAME, CODE, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (7, '登录类型', 'vtl_login_type', null, 1, current_timestamp(), 1, current_timestamp());

-- 字典：停用/启用
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (10001, 'vtl_disabled', 'N', '启用', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (10002, 'vtl_disabled', 'Y', '停用', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
-- 字典：是/否
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (20001, 'vtl_yes_no', 'Y', '是', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (20002, 'vtl_yes_no', 'N', '否', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
-- 字典：成功/失败
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (30001, 'vtl_succeeded', 'Y', '成功', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (30002, 'vtl_succeeded', 'N', '失败', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
-- 字典：用户性别
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (40001, 'vtl_user_gender', 'male', '男', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (40002, 'vtl_user_gender', 'female', '女', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (40003, 'vtl_user_gender', 'unknow', '未知', 3, 'N', null, 1, current_timestamp(), 1, current_timestamp());
-- 字典：登录类型
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (50001, 'vtl_login_type', 'LOGIN', '登录', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (50002, 'vtl_login_type', 'LOGOUT', '注销', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (50003, 'vtl_login_type', 'KICK_OUT', '被踢下线', 3, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (50004, 'vtl_login_type', 'REPLACED', '被顶下线', 4, 'N', null, 1, current_timestamp(), 1, current_timestamp());
-- 字典：菜单类型
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (60001, 'vtl_menu_type', 'DIR', '目录', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (60002, 'vtl_menu_type', 'MENU', '菜单', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (60003, 'vtl_menu_type', 'BTN', '按钮', 3, 'N', null, 1, current_timestamp(), 1, current_timestamp());
-- 字典：菜单打开方式
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (70001, 'vtl_menu_open_type', '_iframe', '系统标签页', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (70002, 'vtl_menu_open_type', '_blank', '浏览器标签页', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());

-- 配置
insert into VTL_CONFIG (ID, NAME, CODE, VAL, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1, '用户管理-初始密码', 'vtl_user_init_password', 'aday.fun', null, 1, current_timestamp(), 1, current_timestamp());

---- TYPE：菜单类型。{ DIR=目录; MENU=菜单; BTN=按钮 }
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1001,               0, 'MENU', '通知公告',        'ep:bell',            'Y',   'system:notice:view',   1,  'NoticeManagePage',  '/vitality/system/notice/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1001001,         1001, 'BTN',  '通知公告-查询',       null,                 'Y',   'system:notice:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1001002,         1001, 'BTN',  '通知公告-创建',       null,                 'Y',   'system:notice:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1001003,         1001, 'BTN',  '通知公告-更新',       null,                 'Y',   'system:notice:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1001004,         1001, 'BTN',  '通知公告-删除',       null,                 'Y',   'system:notice:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1002,               0, 'DIR',       '我的消息',  'ep:chat-dot-round',   'Y',   'system:my:message',     2,  'MyMessagePage',   '/vitality/system/message/index', null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1002001,         1002, 'BTN',  '我的消息-查询',   null,                 'Y',   'system:message:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1002002,         1002, 'BTN',  '我的消息-创建',   null,                 'Y',   'system:message:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1002003,         1002, 'BTN',  '我的消息-更新',   null,                 'Y',   'system:message:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1002004,         1002, 'BTN',  '我的消息-删除',   null,                 'Y',   'system:message:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1003,               0, 'DIR',       '我的流程',  'ri:flow-chart',      'Y',   'system:my:flow',     3,  'MyFlowPage',       '/vitality/system/flow/index', null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1003001,         1003, 'BTN',  '我的流程-查询',   null,                 'Y',   'system:flow:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1003002,         1003, 'BTN',  '我的流程-创建',   null,                 'Y',   'system:flow:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1003003,         1003, 'BTN',  '我的流程-更新',   null,                 'Y',   'system:flow:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1003004,         1003, 'BTN',  '我的流程-删除',   null,                 'Y',   'system:flow:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011,              0, 'DIR',  '系统管理',        'ep:setting',         'Y',   'system:manage:dir',  11,  null,              '/vitality/system/manage',      null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011001,       10011, 'MENU', '菜单管理',        'ep:menu',            'Y',   'system:menu:view',    1,  'MenuManagePage',  '/vitality/system/menu/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011001001, 10011001, 'BTN',  '菜单-查询',       null,                 'Y',   'system:menu:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011001002, 10011001, 'BTN',  '菜单-创建',       null,                 'Y',   'system:menu:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011001003, 10011001, 'BTN',  '菜单-更新',       null,                 'Y',   'system:menu:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011001004, 10011001, 'BTN',  '菜单-删除',       null,                 'Y',   'system:menu:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011002,       10011, 'MENU', '部门管理',        'ri:organization-chart', 'Y',   'system:dept:view',    2,  'DeptManagePage',  '/vitality/system/dept/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011002001, 10011002, 'BTN',  '部门-查询',       null,                 'Y',   'system:dept:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011002002, 10011002, 'BTN',  '部门-创建',       null,                 'Y',   'system:dept:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011002003, 10011002, 'BTN',  '部门-更新',       null,                 'Y',   'system:dept:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011002004, 10011002, 'BTN',  '部门-删除',       null,                 'Y',   'system:dept:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011003,       10011, 'MENU', '岗位管理',        'fa-solid:user-tie',  'Y',   'system:post:view',    3,  'PostManagePage',  '/vitality/system/post/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011003001, 10011003, 'BTN',  '岗位-查询',       null,                 'Y',   'system:post:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011003002, 10011003, 'BTN',  '岗位-创建',       null,                 'Y',   'system:post:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011003003, 10011003, 'BTN',  '岗位-更新',       null,                 'Y',   'system:post:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011003004, 10011003, 'BTN',  '岗位-删除',       null,                 'Y',   'system:post:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011004,       10011, 'MENU', '用户管理',        'ep:user-filled',     'Y',   'system:user:view',    4,  'UserManagePage',  '/vitality/system/user/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011004001, 10011004, 'BTN',  '用户-查询',       null,                 'Y',   'system:user:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011004002, 10011004, 'BTN',  '用户-创建',       null,                 'Y',   'system:user:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011004003, 10011004, 'BTN',  '用户-更新',       null,                 'Y',   'system:user:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011004004, 10011004, 'BTN',  '用户-删除',       null,                 'Y',   'system:user:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011005,       10011, 'MENU', '角色管理',        'fa-solid:users',     'Y',   'system:role:view',    5,  'RoleManagePage',  '/vitality/system/role/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011005001, 10011005, 'BTN',  '角色-查询',       null,                 'Y',   'system:role:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011005002, 10011005, 'BTN',  '角色-创建',       null,                 'Y',   'system:role:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011005003, 10011005, 'BTN',  '角色-更新',       null,                 'Y',   'system:role:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011005004, 10011005, 'BTN',  '角色-删除',       null,                 'Y',   'system:role:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011006,       10011, 'MENU', '分类管理',        'fa-solid:stream',    'Y',   'system:category:view',    6,  'CategoryManagePage',  '/vitality/system/category/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011006001, 10011006, 'BTN',  '分类-查询',       null,                 'Y',   'system:category:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011006002, 10011006, 'BTN',  '分类-创建',       null,                 'Y',   'system:category:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011006003, 10011006, 'BTN',  '分类-更新',       null,                 'Y',   'system:category:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011006004, 10011006, 'BTN',  '分类-删除',       null,                 'Y',   'system:category:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007,       10011, 'MENU', '字典管理',        'fa-solid:book-open', 'Y',   'system:dict:view',        7,  'DictManagePage',  '/vitality/system/dict/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007001, 10011007, 'BTN',  '字典-类型-查询',  null,                 'Y',   'system:dictType:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007002, 10011007, 'BTN',  '字典-类型-创建',  null,                 'Y',   'system:dictType:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007003, 10011007, 'BTN',  '字典-类型-更新',  null,                 'Y',   'system:dictType:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007004, 10011007, 'BTN',  '字典-类型-删除',  null,                 'Y',   'system:dictType:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007005, 10011007, 'BTN',  '字典-数据-查询',  null,                 'Y',   'system:dictData:query',   5,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007006, 10011007, 'BTN',  '字典-数据-创建',  null,                 'Y',   'system:dictData:create',  6,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007007, 10011007, 'BTN',  '字典-数据-更新',  null,                 'Y',   'system:dictData:update',  7,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007008, 10011007, 'BTN',  '字典-数据-删除',  null,                 'Y',   'system:dictData:delete',  8,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011008,       10011, 'MENU', '配置管理',        'ep:set-up',          'Y',   'system:generatorArgs:view',    8,  'ConfigManagePage',  '/vitality/system/generatorArgs/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011008001, 10011008, 'BTN',  '配置-查询',       null,                 'Y',   'system:generatorArgs:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011008002, 10011008, 'BTN',  '配置-创建',       null,                 'Y',   'system:generatorArgs:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011008003, 10011008, 'BTN',  '配置-更新',       null,                 'Y',   'system:generatorArgs:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011008004, 10011008, 'BTN',  '配置-删除',       null,                 'Y',   'system:generatorArgs:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011009,       10011, 'MENU', '文件管理',        'fa-solid:file',      'Y',   'system:oss:view',    9,  'FileManagePage',  '/vitality/system/oss/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011009001, 10011009, 'BTN',  '文件-查询',       null,                 'Y',   'system:oss:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011009002, 10011009, 'BTN',  '文件-创建',       null,                 'Y',   'system:oss:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011009003, 10011009, 'BTN',  '文件-更新',       null,                 'Y',   'system:oss:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011009004, 10011009, 'BTN',  '文件-删除',       null,                 'Y',   'system:oss:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());


insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10021,              0, 'DIR',  '系统监控',        'ep:monitor',         'Y',   'monitor:system:view',  21,  null,              '/vitality/monitor',    null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10021001,       10021, 'MENU', '应用监控',        'fa-solid:chart-line', 'Y',   'monitor:application:query', 1,  'MonitorApplicationPage',  '/vitality/monitor/application/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10022001,       10021, 'MENU', '缓存监控',        'ep:data-line',        'Y',   'monitor:cache:query', 2,  'MonitorCachePage',  '/vitality/monitor/cache/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10023001,       10021, 'MENU', '在线用户',        'fa-solid:user-shield', 'Y',   'monitor:userOnline:view',        3,  'MonitorOnlineUserPage',  '/vitality/monitor/online/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10023001001, 10023001, 'BTN',  '在线用户-查询',       null,              'Y',   'monitor:userOnline:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10023001002, 10023001, 'BTN',  '在线用户-下线',       null,              'Y',   'monitor:userOnline:kickOut',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10024001,       10021, 'MENU', '登录日志',        'ri:file-text-fill',   'Y',   'monitor:logLogin:view',        4,  'MonitorLogLoginPage',  '/vitality/monitor/log/login/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10024001001, 10024001, 'BTN',  '登录日志-查询',       null,              'Y',   'monitor:logLogin:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10024001002, 10024001, 'BTN',  '登录日志-删除',       null,              'Y',   'monitor:logLogin:delete',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10025001,       10021, 'MENU', '操作日志',        'ri:file-text-fill',   'Y',   'monitor:logOperation:view',        5,  'MonitorLogOperationPage',  '/vitality/monitor/log/operation/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10025001001, 10025001, 'BTN',  '操作日志-查询',       null,              'Y',   'monitor:logOperation:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10025001002, 10025001, 'BTN',  '操作日志-删除',       null,              'Y',   'monitor:logOperation:delete',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10026001,       10021, 'MENU', '异常日志',        'ri:file-text-fill',   'Y',   'monitor:logError:view',        6,  'MonitorLogErrorPage',  '/vitality/monitor/log/error/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10026001001, 10026001, 'BTN',  '异常日志-查询',       null,              'Y',   'monitor:logError:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10026001002, 10026001, 'BTN',  '异常日志-删除',       null,              'Y',   'monitor:logError:delete',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());


insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10091,              0, 'DIR',  '开发工具',        'fa-solid:tools',     'Y',   'tool:development:view',  91,  null,              '/vitality/tool',    null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10091001,       10091, 'MENU', '接口文档',        'ep:document',        'Y',   'tool:api:view', 1,  'ToolApiPage',  '/vitality/tool/api',  'http://localhost:8080/doc.html','N',null,1,current_timestamp(),1,current_timestamp());
