--liquibase formatted sql
--changeset admin:2 splitStatements:true

-- 用户 123456
insert into VTL_USER (ID,USERNAME,NICKNAME,PASSWORD,ID_CARD,GENDER,EMAIL,MOBILE,SECRET_KEY,DISABLED,DELETED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1,'admin','管理员','$2a$10$yqsTAbIjiBzENx.sJX1TWewtdoBbQKPTMZsj/BWyJI/k8ymqvTQJO',null,null,null,null,null,'N','N',1,current_timestamp(),1,current_timestamp());
insert into VTL_USER (ID,USERNAME,NICKNAME,PASSWORD,ID_CARD,GENDER,EMAIL,MOBILE,SECRET_KEY,DISABLED,DELETED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (2,'guest','游客','$2a$10$yqsTAbIjiBzENx.sJX1TWewtdoBbQKPTMZsj/BWyJI/k8ymqvTQJO',null,null,null,null,null,'N','N',1,current_timestamp(),1,current_timestamp());

-- 角色
insert into VTL_ROLE (ID, NAME, CODE, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1, '管理员', 'admin', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_ROLE (ID, NAME, CODE, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (2, '普通用户', 'common', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_ROLE (ID, NAME, CODE, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (3, '游客', 'guest', 3, 'N', null, 1, current_timestamp(), 1, current_timestamp());

-- 部门
insert into VTL_DEPT (ID, PARENT_ID, NAME, CODE, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1,           0,        'VTL科技',    'vitality',                 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, CODE, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1001,        1,        '西安分部',   'xi_an',                     1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, CODE, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1001001,     1001,     '财务部',     'xi_an_finance',             1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, CODE, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1001002,     1001,     '研发中心',   'xi_an_development_center',  2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, CODE, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1001002001,  1001002,  '研发一部',   'xi_an_development1',        1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, CODE, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1001002002,  1001002,  '研发二部',   'xi_an_development2',        2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, CODE, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1001003,     1001,     '销售部',     'xi_an_sales',               3, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, CODE, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1002,        1,        '北京分部',   'bei_jing',                  2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, CODE, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1002002,     1002,     '研发一部',   'bei_jing_development1',      1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DEPT (ID, PARENT_ID, NAME, CODE, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1002003,     1002,     '销售部',     'bei_jing_sales',            2, 'N', null, 1, current_timestamp(), 1, current_timestamp());

-- 岗位
insert into VTL_POST (ID, NAME, CODE, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1, '董事长', 'ceo', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_POST (ID, NAME, CODE, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (2, '人力资源', 'hr', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_POST (ID, NAME, CODE, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (3, '开发工程师', 'development_engineer', 3, 'N', null, 1, current_timestamp(), 1, current_timestamp());

-- 字典类型
insert into VTL_DICT_TYPE (ID, NAME, CODE, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1, '停用/启用', 'vtl_disabled', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_TYPE (ID, NAME, CODE, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (2, '是/否', 'vtl_yes_no', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_TYPE (ID, NAME, CODE, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (3, '菜单类型', 'vtl_menu_type', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_TYPE (ID, NAME, CODE, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (4, '菜单打开方式', 'vtl_menu_open_type', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_TYPE (ID, NAME, CODE, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (5, '用户性别', 'vtl_user_gender', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_TYPE (ID, NAME, CODE, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (6, '成功/失败', 'vtl_succeeded', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_TYPE (ID, NAME, CODE, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (7, '登录类型', 'vtl_login_type', null, 1, current_timestamp(), 1, current_timestamp());

-- 字典：停用/启用
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (10001, 'vtl_disabled', 'N', '启用', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (10002, 'vtl_disabled', 'Y', '停用', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
-- 字典：是/否
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (20001, 'vtl_yes_no', 'Y', '是', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (20002, 'vtl_yes_no', 'N', '否', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
-- 字典：成功/失败
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (30001, 'vtl_succeeded', 'Y', '成功', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (30002, 'vtl_succeeded', 'N', '失败', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
-- 字典：用户性别
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (40001, 'vtl_user_gender', 'male', '男', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (40002, 'vtl_user_gender', 'female', '女', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (40003, 'vtl_user_gender', 'unknow', '未知', 3, 'N', null, 1, current_timestamp(), 1, current_timestamp());
-- 字典：登录类型
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (50001, 'vtl_login_type', 'LOGIN', '登录', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (50002, 'vtl_login_type', 'LOGOUT', '注销', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (50003, 'vtl_login_type', 'KICK_OUT', '被踢下线', 3, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (50004, 'vtl_login_type', 'REPLACED', '被顶下线', 4, 'N', null, 1, current_timestamp(), 1, current_timestamp());
-- 字典：菜单类型
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (60001, 'vtl_menu_type', 'DIR', '目录', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (60002, 'vtl_menu_type', 'MENU', '菜单', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (60003, 'vtl_menu_type', 'BTN', '按钮', 3, 'N', null, 1, current_timestamp(), 1, current_timestamp());
-- 字典：菜单打开方式
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (70001, 'vtl_menu_open_type', '_iframe', '系统标签页', 1, 'N', null, 1, current_timestamp(), 1, current_timestamp());
insert into VTL_DICT_DATA (ID, CODE, VAL, LABEL, SEQ, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (70002, 'vtl_menu_open_type', '_blank', '浏览器标签页', 2, 'N', null, 1, current_timestamp(), 1, current_timestamp());

-- 配置
insert into VTL_CONFIG (ID, NAME, CODE, VAL, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) values (1, '用户管理-初始密码', 'vtl_user_init_password', 'home.aday.fun', null, 1, current_timestamp(), 1, current_timestamp());

---- TYPE：菜单类型。{ DIR=目录; MENU=菜单; BTN=按钮 }
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1001,               0, 'DIR',       '我的消息',  'ep:chat-dot-round',   'Y',   'system:my:message',     1,  'MyMessagePage',   '/system/message/index', null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1001001,         1001, 'BTN',  '我的消息-查询',   null,                 'Y',   'system:message:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1001002,         1001, 'BTN',  '我的消息-创建',   null,                 'Y',   'system:message:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1001003,         1001, 'BTN',  '我的消息-更新',   null,                 'Y',   'system:message:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (1001004,         1001, 'BTN',  '我的消息-删除',   null,                 'Y',   'system:message:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011,              0, 'DIR',  '系统管理',        'ep:setting',         'Y',   'system:manage:dir',  11,  null,              '/system',             null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011001,       10011, 'MENU', '菜单管理',        'ep:menu',            'Y',   'system:menu:view',    1,  'MenuManagePage',  '/system/menu/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011001001, 10011001, 'BTN',  '菜单-查询',       null,                 'Y',   'system:menu:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011001002, 10011001, 'BTN',  '菜单-创建',       null,                 'Y',   'system:menu:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011001003, 10011001, 'BTN',  '菜单-更新',       null,                 'Y',   'system:menu:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011001004, 10011001, 'BTN',  '菜单-删除',       null,                 'Y',   'system:menu:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011002,       10011, 'MENU', '部门管理',        'ri:organization-chart', 'Y',   'system:dept:view',    2,  'DeptManagePage',  '/system/dept/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011002001, 10011002, 'BTN',  '部门-查询',       null,                 'Y',   'system:dept:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011002002, 10011002, 'BTN',  '部门-创建',       null,                 'Y',   'system:dept:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011002003, 10011002, 'BTN',  '部门-更新',       null,                 'Y',   'system:dept:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011002004, 10011002, 'BTN',  '部门-删除',       null,                 'Y',   'system:dept:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011003,       10011, 'MENU', '岗位管理',        'fa-solid:user-tie',  'Y',   'system:post:view',    3,  'PostManagePage',  '/system/post/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011003001, 10011003, 'BTN',  '岗位-查询',       null,                 'Y',   'system:post:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011003002, 10011003, 'BTN',  '岗位-创建',       null,                 'Y',   'system:post:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011003003, 10011003, 'BTN',  '岗位-更新',       null,                 'Y',   'system:post:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011003004, 10011003, 'BTN',  '岗位-删除',       null,                 'Y',   'system:post:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011004,       10011, 'MENU', '用户管理',        'ep:user-filled',     'Y',   'system:user:view',    4,  'UserManagePage',  '/system/user/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011004001, 10011004, 'BTN',  '用户-查询',       null,                 'Y',   'system:user:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011004002, 10011004, 'BTN',  '用户-创建',       null,                 'Y',   'system:user:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011004003, 10011004, 'BTN',  '用户-更新',       null,                 'Y',   'system:user:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011004004, 10011004, 'BTN',  '用户-删除',       null,                 'Y',   'system:user:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011005,       10011, 'MENU', '角色管理',        'fa-solid:users',     'Y',   'system:role:view',    5,  'RoleManagePage',  '/system/role/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011005001, 10011005, 'BTN',  '角色-查询',       null,                 'Y',   'system:role:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011005002, 10011005, 'BTN',  '角色-创建',       null,                 'Y',   'system:role:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011005003, 10011005, 'BTN',  '角色-更新',       null,                 'Y',   'system:role:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011005004, 10011005, 'BTN',  '角色-删除',       null,                 'Y',   'system:role:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011006,       10011, 'MENU', '分类管理',        'fa-solid:stream',    'Y',   'system:category:view',    6,  'CategoryManagePage',  '/system/category/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011006001, 10011006, 'BTN',  '分类-查询',       null,                 'Y',   'system:category:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011006002, 10011006, 'BTN',  '分类-创建',       null,                 'Y',   'system:category:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011006003, 10011006, 'BTN',  '分类-更新',       null,                 'Y',   'system:category:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011006004, 10011006, 'BTN',  '分类-删除',       null,                 'Y',   'system:category:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007,       10011, 'MENU', '字典管理',        'fa-solid:book-open', 'Y',   'system:dict:view',        7,  'DictManagePage',  '/system/dict/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007001, 10011007, 'BTN',  '字典-类型-查询',  null,                 'Y',   'system:dictType:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007002, 10011007, 'BTN',  '字典-类型-创建',  null,                 'Y',   'system:dictType:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007003, 10011007, 'BTN',  '字典-类型-更新',  null,                 'Y',   'system:dictType:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007004, 10011007, 'BTN',  '字典-类型-删除',  null,                 'Y',   'system:dictType:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007005, 10011007, 'BTN',  '字典-数据-查询',  null,                 'Y',   'system:dictData:query',   5,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007006, 10011007, 'BTN',  '字典-数据-创建',  null,                 'Y',   'system:dictData:create',  6,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007007, 10011007, 'BTN',  '字典-数据-更新',  null,                 'Y',   'system:dictData:update',  7,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011007008, 10011007, 'BTN',  '字典-数据-删除',  null,                 'Y',   'system:dictData:delete',  8,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011008,       10011, 'MENU', '配置管理',        'ep:set-up',          'Y',   'system:config:view',    8,  'ConfigManagePage',  '/system/config/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011008001, 10011008, 'BTN',  '配置-查询',       null,                 'Y',   'system:config:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011008002, 10011008, 'BTN',  '配置-创建',       null,                 'Y',   'system:config:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011008003, 10011008, 'BTN',  '配置-更新',       null,                 'Y',   'system:config:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011008004, 10011008, 'BTN',  '配置-删除',       null,                 'Y',   'system:config:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011009,       10011, 'MENU', '文件管理',        'fa-solid:file',      'Y',   'system:oss:view',    9,  'FileManagePage',  '/system/file/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011009001, 10011009, 'BTN',  '文件-查询',       null,                 'Y',   'system:oss:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011009002, 10011009, 'BTN',  '文件-创建',       null,                 'Y',   'system:oss:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011009003, 10011009, 'BTN',  '文件-更新',       null,                 'Y',   'system:oss:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011009004, 10011009, 'BTN',  '文件-删除',       null,                 'Y',   'system:oss:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011011,       10011, 'MENU', '通知公告',        'ep:mute-notification', 'Y',   'system:notice:view',   11,  'NoticeManagePage',  '/system/notice/index',  null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011011001, 10011011, 'BTN',  '通知-查询',       null,                 'Y',   'system:notice:query',   1,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011011002, 10011011, 'BTN',  '通知-创建',       null,                 'Y',   'system:notice:create',  2,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011011003, 10011011, 'BTN',  '通知-更新',       null,                 'Y',   'system:notice:update',  3,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());
insert into VTL_MENU (ID,PARENT_ID,"TYPE",TITLE,ICON,SHOW_LINK,PERMISSION,SEQ,ROUTER_NAME,ROUTER_PATH,IFRAME,DISABLED,REMARK,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (10011011004, 10011011, 'BTN',  '通知-删除',       null,                 'Y',   'system:notice:delete',  4,  null,               null,                 null,'N',null,1,current_timestamp(),1,current_timestamp());

--INSERT INTO VTL_MENU (ID, PARENT_ID, TITLE, TYPE, PERMISSION, SEQ, ICON, URL, OPEN_TYPE, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) VALUES (10021,          0,       '系统监控',  'DIR',  'monitor',                  21, null, null, null, 'N', null, 1, CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP());
--INSERT INTO VTL_MENU (ID, PARENT_ID, TITLE, TYPE, PERMISSION, SEQ, ICON, URL, OPEN_TYPE, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) VALUES (10021001,       10021,    '应用监控',  'MENU', 'monitor:application',      1, null, null, null, 'N', null, 1, CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP());
--
--INSERT INTO VTL_MENU (ID, PARENT_ID, TITLE, TYPE, PERMISSION, SEQ, ICON, URL, OPEN_TYPE, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) VALUES (10021002,       10021,    '在线用户',      'MENU', 'monitor:online:user',        2, null, null, null, 'N', null, 1, CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP());
--INSERT INTO VTL_MENU (ID, PARENT_ID, TITLE, TYPE, PERMISSION, SEQ, ICON, URL, OPEN_TYPE, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) VALUES (10021002001,    10021002, '在线用户-查询',  'BTN',  'monitor:online:user:query',  1, null, null, null, 'N', null, 1, CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP());
--INSERT INTO VTL_MENU (ID, PARENT_ID, TITLE, TYPE, PERMISSION, SEQ, ICON, URL, OPEN_TYPE, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) VALUES (10021002002,    10021002, '在线用户-下线',  'BTN',  'monitor:online:user:delete', 2, null, null, null, 'N', null, 1, CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP());
--
--INSERT INTO VTL_MENU (ID, PARENT_ID, TITLE, TYPE, PERMISSION, SEQ, ICON, URL, OPEN_TYPE, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) VALUES (10021003,       10021,    '登录日志',      'MENU', 'system:logLogin',        3, null, null, null, 'N', null, 1, CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP());
--INSERT INTO VTL_MENU (ID, PARENT_ID, TITLE, TYPE, PERMISSION, SEQ, ICON, URL, OPEN_TYPE, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) VALUES (10021003001,    10021003, '登录日志-查询',  'BTN',  'system:logLogin:query',  1, null, null, null, 'N', null, 1, CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP());
--INSERT INTO VTL_MENU (ID, PARENT_ID, TITLE, TYPE, PERMISSION, SEQ, ICON, URL, OPEN_TYPE, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) VALUES (10021003002,    10021003, '登录日志-删除',  'BTN',  'system:logLogin:delete', 2, null, null, null, 'N', null, 1, CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP());
--
--INSERT INTO VTL_MENU (ID, PARENT_ID, TITLE, TYPE, PERMISSION, SEQ, ICON, URL, OPEN_TYPE, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) VALUES (10021004,       10021,    '操作日志',      'MENU', 'system:logOperation',        4, null, null, null, 'N', null, 1, CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP());
--INSERT INTO VTL_MENU (ID, PARENT_ID, TITLE, TYPE, PERMISSION, SEQ, ICON, URL, OPEN_TYPE, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) VALUES (10021004001,    10021004, '操作日志-查询',  'BTN',  'system:logOperation:query',  1, null, null, null, 'N', null, 1, CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP());
--INSERT INTO VTL_MENU (ID, PARENT_ID, TITLE, TYPE, PERMISSION, SEQ, ICON, URL, OPEN_TYPE, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) VALUES (10021004002,    10021004, '操作日志-删除',  'BTN',  'system:logOperation:delete', 2, null, null, null, 'N', null, 1, CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP());
--
--INSERT INTO VTL_MENU (ID, PARENT_ID, TITLE, TYPE, PERMISSION, SEQ, ICON, URL, OPEN_TYPE, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) VALUES (10021005,       10021,    '异常日志',      'MENU', 'system:logError',        5, null, null, null, 'N', null, 1, CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP());
--INSERT INTO VTL_MENU (ID, PARENT_ID, TITLE, TYPE, PERMISSION, SEQ, ICON, URL, OPEN_TYPE, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) VALUES (10021005001,    10021005, '异常日志-查询',  'BTN',  'system:logError:query',  1, null, null, null, 'N', null, 1, CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP());
--INSERT INTO VTL_MENU (ID, PARENT_ID, TITLE, TYPE, PERMISSION, SEQ, ICON, URL, OPEN_TYPE, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) VALUES (10021005002,    10021005, '异常日志-删除',  'BTN',  'system:logError:delete', 2, null, null, null, 'N', null, 1, CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP());
--
--INSERT INTO VTL_MENU (ID, PARENT_ID, TITLE, TYPE, PERMISSION, SEQ, ICON, URL, OPEN_TYPE, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) VALUES (10081,          0, '通知公告',   'MENU',  'system:notice',       81, null, null, null, 'N', null, 1, CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP());
--INSERT INTO VTL_MENU (ID, PARENT_ID, TITLE, TYPE, PERMISSION, SEQ, ICON, URL, OPEN_TYPE, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) VALUES (10081001,    10081, '用户-查询',  'BTN',  'system:notice:query',  1, null, null, null, 'N', null, 1, CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP());
--INSERT INTO VTL_MENU (ID, PARENT_ID, TITLE, TYPE, PERMISSION, SEQ, ICON, URL, OPEN_TYPE, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) VALUES (10081002,    10081, '用户-创建',  'BTN',  'system:notice:create', 2, null, null, null, 'N', null, 1, CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP());
--INSERT INTO VTL_MENU (ID, PARENT_ID, TITLE, TYPE, PERMISSION, SEQ, ICON, URL, OPEN_TYPE, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) VALUES (10081003,    10081, '用户-更新',  'BTN',  'system:notice:update', 3, null, null, null, 'N', null, 1, CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP());
--INSERT INTO VTL_MENU (ID, PARENT_ID, TITLE, TYPE, PERMISSION, SEQ, ICON, URL, OPEN_TYPE, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) VALUES (10081004,    10081, '用户-删除',  'BTN',  'system:notice:delete', 4, null, null, null, 'N', null, 1, CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP());
