DROP TABLE IF EXISTS QB_ROLE;
CREATE TABLE QB_ROLE (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '角色ID',
    name VARCHAR(30) NOT NULL COMMENT '角色名称',
    parent_id BIGINT NOT NULL DEFAULT 0 COMMENT '父角色ID',
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP comment '更新时间',
	create_by VARCHAR(64) NOT NULL COMMENT '创建者',
	update_by VARCHAR(64) NOT NULL COMMENT '更新者',
    PRIMARY KEY (id),
    UNIQUE KEY QB_ROLE_INDEX_NAME (name) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色信息表';


DROP TABLE IF EXISTS QB_USER;
CREATE TABLE QB_USER (
    id BIGINT NOT NULL COMMENT '用户ID',
    username VARCHAR(64) NOT NULL COMMENT '登录账号/用户名',
    password VARCHAR(128) DEFAULT NULL COMMENT '密码',
    nickname VARCHAR(64) DEFAULT NULL COMMENT '用户昵称',
    deleted INT NOT NULL DEFAULT 0 COMMENT '逻辑删除。帐号状态。0 or 1',
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP comment '更新时间',
	create_by VARCHAR(64) NOT NULL COMMENT '创建者',
	update_by VARCHAR(64) NOT NULL COMMENT '更新者',
    PRIMARY KEY (id),
    UNIQUE KEY QB_USER_INDEX_USERNAME (username) USING BTREE,
    UNIQUE KEY QB_USER_INDEX_NICKNAME (nickname) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户信息表';


DROP TABLE IF EXISTS QB_USER_ROLE;
CREATE TABLE QB_USER_ROLE (
    id BIGINT NOT NULL COMMENT 'ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    role_id BIGINT NOT NULL COMMENT '角色ID',
  	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP comment '更新时间',
	create_by VARCHAR(64) NOT NULL COMMENT '创建者',
	update_by VARCHAR(64) NOT NULL COMMENT '更新者',
    PRIMARY KEY (id),
    UNIQUE KEY QB_USER_ROLE_INDEX_USER_ROLE (user_id, role_id) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色和用户关联表';


DROP TABLE IF EXISTS QB_AUTH;
CREATE TABLE QB_AUTH (
    id BIGINT NOT NULL COMMENT 'ID',
    auth_key VARCHAR(60) NOT NULL COMMENT '权限唯一标识关键词。如：system_user_insert, system_user_update',
    auth_name VARCHAR(60) NOT NULL COMMENT '权限描述。如：用户新增、用户修改、用户查询等',
  	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP comment '更新时间',
	create_by VARCHAR(64) NOT NULL COMMENT '创建者',
	update_by VARCHAR(64) NOT NULL COMMENT '更新者',
    PRIMARY KEY (id),
    UNIQUE KEY QB_AUTH_INDEX_AUTH_KEY (auth_key) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='权限表';


DROP TABLE IF EXISTS QB_ROLE_AUTH;
CREATE TABLE QB_ROLE_AUTH (
    id BIGINT NOT NULL COMMENT 'ID',
    role_id BIGINT NOT NULL COMMENT '角色ID',
    auth_id BIGINT NOT NULL COMMENT '权限ID',
  	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP comment '更新时间',
	create_by VARCHAR(64) NOT NULL COMMENT '创建者',
	update_by VARCHAR(64) NOT NULL COMMENT '更新者',
    PRIMARY KEY (id),
    UNIQUE KEY QB_ROLE_AUTH_INDEX_ROLE_AUTH (role_id, auth_id) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色和权限关联表';


DROP TABLE IF EXISTS QB_LOGIN_LOG;
CREATE TABLE QB_LOGIN_LOG (
    id BIGINT NOT NULL COMMENT 'ID',
    username VARCHAR(64) DEFAULT NULL COMMENT '登录账号',
    login_type VARCHAR(6) DEFAULT NULL COMMENT '登录类型（LOGIN or LOGOUT）。 枚举类 LoginType',
    login_status VARCHAR(7) NOT NULL COMMENT '登录状态（SUCCESS or FAILURE）。 枚举类 LoginStatus',
    ip VARCHAR(46) DEFAULT NULL COMMENT '登录/登出IP地址',
    os VARCHAR(50) DEFAULT NULL COMMENT '操作系统',
    browser VARCHAR(50) DEFAULT NULL COMMENT '浏览器类型',
    message VARCHAR(255) DEFAULT NULL COMMENT '提示消息',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP comment '更新时间',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='登录日志表';
