-- h2
-- postgres
-- mysql
insert into VT_MENU (ID,PARENT_ID,TYPE,TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (${generatedId}00,                0,   'MENU', '${entityName}管理', '${entityName}Page',   '/vita${requestMapping}/index',  null,   9,null,'ep:grid',       null,null,null,null,'${module}:${entityPropertyName}:view',null,'N','N','N','N','Y','Y',1,current_timestamp(),1,current_timestamp());
insert into VT_MENU (ID,PARENT_ID,TYPE,TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (${generatedId}01, ${generatedId}00,   'BTN',  '${entityName}-查询',null,           null,                           null,   1,null,null,            null,null,null,null,'${module}:${entityPropertyName}:query',null,'N','N','N','N','Y','Y',1,current_timestamp(),1,current_timestamp());
insert into VT_MENU (ID,PARENT_ID,TYPE,TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (${generatedId}02, ${generatedId}00,   'BTN',  '${entityName}-创建',null,           null,                           null,   2,null,null,            null,null,null,null,'${module}:${entityPropertyName}:create',null,'N','N','N','N','Y','Y',1,current_timestamp(),1,current_timestamp());
insert into VT_MENU (ID,PARENT_ID,TYPE,TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (${generatedId}03, ${generatedId}00,   'BTN',  '${entityName}-更新',null,           null,                           null,   3,null,null,            null,null,null,null,'${module}:${entityPropertyName}:update',null,'N','N','N','N','Y','Y',1,current_timestamp(),1,current_timestamp());
insert into VT_MENU (ID,PARENT_ID,TYPE,TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (${generatedId}04, ${generatedId}00,   'BTN',  '${entityName}-删除',null,           null,                           null,   4,null,null,            null,null,null,null,'${module}:${entityPropertyName}:delete',null,'N','N','N','N','Y','Y',1,current_timestamp(),1,current_timestamp());

-- oracle
insert into VT_MENU (ID,PARENT_ID,TYPE,TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (${generatedId}00,                0,   'MENU', '${entityName}管理', '${entityName}Page',   '/vita${requestMapping}/index',  null,   9,null,'ep:grid',       null,null,null,null,'${module}:${entityPropertyName}:view',null,'N','N','N','N','Y','Y',1,sysdate,1,sysdate);
insert into VT_MENU (ID,PARENT_ID,TYPE,TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (${generatedId}01, ${generatedId}00,   'BTN',  '${entityName}-查询',null,           null,                           null,   1,null,null,            null,null,null,null,'${module}:${entityPropertyName}:query',null,'N','N','N','N','Y','Y',1,sysdate,1,sysdate);
insert into VT_MENU (ID,PARENT_ID,TYPE,TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (${generatedId}02, ${generatedId}00,   'BTN',  '${entityName}-创建',null,           null,                           null,   2,null,null,            null,null,null,null,'${module}:${entityPropertyName}:create',null,'N','N','N','N','Y','Y',1,sysdate,1,sysdate);
insert into VT_MENU (ID,PARENT_ID,TYPE,TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (${generatedId}03, ${generatedId}00,   'BTN',  '${entityName}-更新',null,           null,                           null,   3,null,null,            null,null,null,null,'${module}:${entityPropertyName}:update',null,'N','N','N','N','Y','Y',1,sysdate,1,sysdate);
insert into VT_MENU (ID,PARENT_ID,TYPE,TITLE,ROUTER_NAME,ROUTER_PATH,COMPONENT_PATH,SEQ,REDIRECT,ICON,EXTRA_ICON,ENTER_TRANSITION,LEAVE_TRANSITION,ACTIVE_PATH,PERMISSION,IFRAME_SRC,IFRAME_LOADING,KEEP_ALIVE,HIDDEN_TAG,FIXED_TAG,SHOW_LINK,SHOW_PARENT,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) values (${generatedId}04, ${generatedId}00,   'BTN',  '${entityName}-删除',null,           null,                           null,   4,null,null,            null,null,null,null,'${module}:${entityPropertyName}:delete',null,'N','N','N','N','Y','Y',1,sysdate,1,sysdate);
