--liquibase formatted sql
--changeset admin:2 splitStatements:true
-- 用户
INSERT INTO VTL_USER (ID,USERNAME,NICKNAME,PASSWORD,ID_CARD,GENDER,EMAIL,MOBILE,SECRET_KEY,DISABLED,DELETED,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) VALUES (1821823689714118657,'admin','管理员','$2a$10$GqFUQRFTYHB/3ck3z7tL/OM7MkhfrS/MXdLp/DlKr.HXYPVp7nGL6',NULL,NULL,NULL,NULL,NULL,'N','N',1,CURRENT_TIMESTAMP(),1,CURRENT_TIMESTAMP());

