INSERT INTO VTL_MENU (ID, PARENT_ID, TITLE, TYPE, PERMISSION, SEQ, ICON, URL, OPEN_TYPE, SYSTEM_DEFAULT, DISABLED, REMARK, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME) VALUES (ID, 0, '', 1, 'system:', 1, null, null, '_iframe', 1, 0, null, 1, CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP());

INSERT INTO ${name} (${fieldNames}) VALUES (ID, ......, 1, CURRENT_TIMESTAMP(), 1, CURRENT_TIMESTAMP());